---
title: "clases de R"
author: "Sergio del Carpio"
format: html
editor_options: 
  chunk_output_type: console
---

#Diseños experimentales

##DCA

DOSIS DE FERTILIZACION NITROGENADA:

- 0
- 50
- 100
- 150
Rep: 5

```{r}

if(!require(agricolae))
  install.packages("agricolae")
library(agricolae)
dosis <- c(0, 50, 100, 150)
repeticiones <- 5
dca <- design.crd(trt = dosis, r = repeticiones, seed = 123)
print(dca$book)
```




## DBCA

Factor -> variedades de papa: canchan y peruanita

```{r}
if(!require(agricolae)) install.packages("agricolae")

library(agricolae)
dosis <- c(0, 50, 100, 150)
variedades <- c("Canchan", "Peruanita")

bloques <- 5
trt<-c(4,2) # factorial 4x2
outdesign <-design.ab(trt = trt,r=5)

str(outdesign)
book<-outdesign$book
book
```


#Analisis de datos


```{r}

library(readxl)
fb <- read_excel("LA MOLINA 2014 POTATO WUE (FB).xlsx", 
    sheet = "fb")
View(fb)
str(fb)

```

##Modelo estadistico

```{r}
modelo <- aov(formula = lfa ~ riego + geno +riego*geno + bloque, data =fb)


anova(modelo)

plot(modelo)

```


## Comparación de medias

```{r}
library(agricolae)

mc <- agricolae::duncan.test(y= modelo, trt = c("riego", "geno"))

mc

str(mc)


```

```{r}
library(emmeans)
library(multcomp)
library(tidyverse)

mc<- emmeans(modelo, ~ riego | geno) %>% 
  cld(letters = letters, reversed = T)

mc
```


##Grafico


```{r}
library(inti)
plot_smr(data = mc
         , type = "bar"
         , x = "geno"
         , y = "emmean"
         , group = "riego"
         , sig = ".group"
         , error = "SE"
         , ylimits = c(0, 12000, 2000)
)
```


